function [fields,scale_fields,fmt_fields,factor_fields,default_values]=init_fields(varargin)

angle_fmt='int16';
angle_factor=1/500;
phi_factor=1/100;

db_diff_fmt='single';
db_diff_factor=1;

fish_fmt='uint16';
fish_factor=1/1000;

mot_comp_fmt='uint16';
mot_comp_factor=1/500;

% db_fmt='uint16';
% db_factor=-1/300;

db_fmt='single';
db_factor=1;

uint_fmt='uint8';
int_fmt='int8';
uint_factor=1;
int_factor = 1/2;

uint32_fmt = 'uint32'; 

lin_fmt='single';
comp_lin_fmt='double';
lin_factor=1;

velocity_fmt = 'int16';
velocity_fact = 1/1e3;


% bool_fmt='int8';
% bool_factor=1;

fields={'power',...
    'alongangle','acrossangle',...
    'sp','sv',...
    'img_intensity',...
    'wc_data',...
    'feature_id','feature_sv',...
    'powerunmatched','y_real','y_imag','y_real_filtered','y_imag_filtered','spunmatched','svunmatched',...
    'powerdenoised','svdenoised','spdenoised','snr',...
    'singletarget',  'fishdensity', 'motioncompensation',...
    'acrossphi','alongphi' 'khz' 'velocity_north' 'velocity_east' 'velocity_down' 'velocity' ...
    'correlation',...
    'comp_sig_1_real','comp_sig_2_real','comp_sig_3_real','comp_sig_4_real',...
    'comp_sig_1_imag','comp_sig_2_imag','comp_sig_3_imag','comp_sig_4_imag',...
    'comp_sig_1','comp_sig_2','comp_sig_3','comp_sig_4', ...
    'y', 'y_filtered'};

scale_fields={'lin',...
    'angle','angle',...
    'db','db',...
    'db',...
    'db',...
    'id','db',...
    'lin','lin','lin','lin','lin','db','db',...
    'lin','db','db','db',...
    'db','density','db',...
    'angle','angle','db_diff','speed','speed','speed','speed',...
    'lin',...
    'lin','lin','lin','lin',...
    'lin','lin','lin','lin',...
    'lin','lin','lin','lin',...
    'lin','lin'};

fmt_fields={lin_fmt...
    angle_fmt angle_fmt...
    db_fmt db_fmt...
    uint_fmt ...
    int_fmt ...
    uint32_fmt db_fmt ...
    lin_fmt lin_fmt lin_fmt lin_fmt lin_fmt db_fmt db_fmt...   
    lin_fmt db_fmt db_fmt db_fmt...
    db_fmt fish_fmt mot_comp_fmt...
    angle_fmt angle_fmt db_diff_fmt velocity_fmt velocity_fmt velocity_fmt velocity_fmt,...
    uint_fmt ...
    lin_fmt lin_fmt lin_fmt lin_fmt ...
    lin_fmt lin_fmt lin_fmt lin_fmt ...
    comp_lin_fmt comp_lin_fmt comp_lin_fmt comp_lin_fmt ...
    comp_lin_fmt comp_lin_fmt};

factor_fields=[lin_factor...
    angle_factor angle_factor...
    db_factor db_factor...
    uint_factor ...
    int_factor ...
    uint_factor db_factor ...
    lin_factor lin_factor lin_factor lin_factor lin_factor db_factor db_factor...
    lin_factor db_factor db_factor -db_factor...
    db_factor fish_factor mot_comp_factor...
    phi_factor phi_factor db_diff_factor velocity_fact velocity_fact velocity_fact velocity_fact...
    uint_factor ...
    lin_factor lin_factor lin_factor lin_factor ...
    lin_factor lin_factor lin_factor lin_factor ...
    lin_factor lin_factor lin_factor lin_factor ...
    lin_factor lin_factor];

default_values=[0 ...
    0 0 ...
    -999 -999 ...
    0 ...
    -999 ...
    0 -999 ...
    0 0 0 0 0 -999 -999 ...
    0 -999 -999 -999 ...
    -999 0 0 ...
    0 0 0 nan nan nan nan ...
    0 ...
    0 0 0 0 ...
    0 0 0 0 ...
    0 0 0 0 ...
    0 0];

if nargin >= 1
    idx = find(strcmpi(fields,varargin{1}));
    if ~isempty(idx)
        fields = fields(idx);
        scale_fields = scale_fields(idx);
        fmt_fields = fmt_fields(idx);
        factor_fields = factor_fields(idx);
        default_values = default_values(idx);
    end
end



