function   db_to_cal_struct_cell = translate_db_to_cal_cell()

db_to_cal_struct_cell = {{'calibration_channel_ID','CID'},...
    {'calibration_frequency','FREQ'},...
    {'calibration_gain','G0'},...
    {'calibration_psi','EQA'},...
    {'calibration_sacorrect','SACORRECT'}, ...
    {'calibration_phi_athwart','BeamWidthAthwartship'},...
    {'calibration_phi_athwart_offset','AngleOffsetAthwartship'}, ...
    {'calibration_phi_along','BeamWidthAlongship'},...
    {'calibration_phi_along_offset','AngleOffsetAlongship'},...
    {'calibration_rms','RMS'},...
    {'calibration_depth','depth'},...
    {'calibration_sphere_range_av','sphere_range_av'},...
    {'calibration_sphere_range_std','sphere_range_std'},...
    {'calibration_nb_echoes','nb_echoes'},...
    {'calibration_nb_central_echoes','nb_central_echoes'},...
    {'calibration_sphere_ts','sphere_ts'},...
    {'calibration_sphere_type','sphere_type'},...
    {'calibration_up_or_down_cast','up_or_down_cast'}...
    };

end