function create_vrt_file(filename, table_names,lon_cols,lat_cols)

[path,fname,fend] = fileparts(filename);

filename_vrt = fullfile(path,[fname '.vrt']);
fid = fopen(filename_vrt,"w+");

if fid ==-1
    fprintf('Could not create .vrt file for file %s',filename);
    return;
end

fprintf(fid,'<OGRVRTDataSource>\n');
for it = 1:numel(table_names)
    fprintf(fid,['   <OGRVRTLayer name="%s">\n'  ...
        '       <SrcDataSource relativeToVRT="1">%s</SrcDataSource>\n'...
        '       <SrcLayer>%s</SrcLayer>\n'...
        '       <GeometryType>wkbPoint</GeometryType>\n'...
        '       <LayerSRS>WGS84</LayerSRS>\n'...
        '    <GeometryField encoding="PointFromColumns" x="%s" y="%s"/>\n'...
        '   </OGRVRTLayer>\n'],...
        table_names{it},...
        [fname fend],...
        table_names{it},...
        lon_cols{it},...
        lat_cols{it});
end
fprintf(fid,'</OGRVRTDataSource>');

fclose(fid);