function feature_struct = init_ft_struct(nb_features)

feature_struct = struct(...
    'E',nan(1,nb_features),...
    'N',nan(1,nb_features),...
    'H',nan(1,nb_features),...
    'Zone',nan(1,nb_features),...
    'AlongDist',nan(1,nb_features),...
    'AcrossDist',nan(1,nb_features),...
    'Range',nan(1,nb_features),...
    'Idx_r',nan(1,nb_features),...
    'Idx_ping',nan(1,nb_features),...
    'Idx_beam',nan(1,nb_features),...
    'Sv',nan(1,nb_features),...
    'Time',nan(1,nb_features),...
    'id',nan(1,nb_features));

