function [Along_pos,Across_pos,z]=angles_to_pos_vec(...
    Range,AcrossAngle,AlongAngle,...
    Heave,Roll,Pitch,Yaw,...
    RollOffset,...
    PitchOffset,...
    YawOffset,... 
    AlongOffset,...
    AcrossOffset,...
    Zoffset, ...
    roll_comp_bool, ...
    pitch_comp_bool, ...
    yaw_comp_bool, ...
    heave_comp_bool ...
   )

attitude_mat = double(create_attitude_matrix(shiftdim(AcrossAngle,-2),shiftdim(AlongAngle,-2),zeros(1,1,numel(Range))));

pos_in_trans_right = pagemtimes(attitude_mat,[zeros(1,1,numel(Range));zeros(1,1,numel(Range));shiftdim(Range,-2)]);

attitude_mat_3 = double(create_attitude_matrix(shiftdim(Roll*roll_comp_bool+RollOffset,-2),shiftdim(Pitch*pitch_comp_bool+PitchOffset,-2),shiftdim(Yaw*yaw_comp_bool+YawOffset,-2)));
attitude_mat_3_trans = double(create_attitude_matrix(shiftdim(Roll,-2),shiftdim(Pitch,-2),shiftdim(Yaw,-2)));

pos_mat = pagemtimes(attitude_mat_3,(pos_in_trans_right)) ...
    + pagemtimes(attitude_mat_3_trans,double([AlongOffset;AcrossOffset;Zoffset])) ...
    + double([zeros(1,1,numel(Range));zeros(1,1,numel(Range));shiftdim(Heave*heave_comp_bool,-2)]);

Along_pos=pos_mat(1,:)';
Across_pos=pos_mat(2,:)';
z=pos_mat(3,:)';

end