function [Along_pos,Across_pos,z]=angles_to_pos_single(...
    Range,AcrossAngle,AlongAngle,...
    Heave,Roll,Pitch,Yaw,...
    RollOffset,...
    PitchOffset,...
    YawOffset,... 
    AlongOffset,...
   AcrossOffset,...
   Zoffset ...
   )

attitude_mat=double(create_attitude_matrix(AcrossAngle,AlongAngle,0));

pos_in_trans_right=attitude_mat*[0;0;Range];

attitude_mat_3=double(create_attitude_matrix(Roll+RollOffset,Pitch+PitchOffset,Yaw+YawOffset));

pos_mat=attitude_mat_3*(pos_in_trans_right+double([AlongOffset;AcrossOffset;Zoffset]))+double([0;0;Heave]);

Along_pos=pos_mat(1);
Across_pos=pos_mat(2);
z=pos_mat(3);

end