function createlogbookTable(dbconn)

logbook_table=dbconn.fetch('SELECT name FROM sqlite_master WHERE type=''table'' AND name=''logbook''');

if isempty(logbook_table)
    createlogbookTable_str = ['create table logbook ' ...
        '(Filename TEXT DEFAULT NULL,'...
        'Snapshot INTEGER DEFAULT 0,'...
        'Stratum VARCHAR DEFAULT NULL,'...
        'Type VARCHAR DEFAULT NULL,'...
        'Transect INTEGER DEFAULT 0,'...
        'StartTime TIMESTAMP,'...%yyyy-mm-dd HH:MM:SS
        'EndTime TIMESTAMP,'...
        'Comment TEXT DEFAULT NULL,'...
        'PRIMARY KEY(Filename,StartTime) ON CONFLICT REPLACE,'...
        'UNIQUE(Filename,EndTime) ON CONFLICT REPLACE,'...
        'CHECK (EndTime>=StartTime))'];
    dbconn.exec(createlogbookTable_str);
    
else
    isthereatypecolumn=dbconn.fetch('SELECT sql FROM sqlite_master WHERE type=''table'' AND name=''logbook''');
    if ~contains(isthereatypecolumn.sql{1},'Type')
        dbconn.exec(['ALTER TABLE logbook '...
            'ADD Type VARCHAR DEFAULT " "']);
    end 
end